### ISSUE TITLE
Why EPS?

### ISSUE THREAD

**Issue by 8lall0** [larryhynes/nojpeg#12]
Srsly, why EPS and not SVG?

**Comment by larryhynes** [comment]
That's a good question, and one that has been asked before. (That's why both SVG and PDF get a mention.) My background is in design for print, where EPS would be the _de facto_ standard - due in no small part to its support for Pantone spot colours and CMYK, and also a long history of very wide adoption. In the digital space, of course, one can happily live with SVG alone, but I wouldn't like to submit an SVG file to a small rural print shop to have my business cards printed, for example. And I'm not sure what sort of results one might get if one were to embed an SVG in - for example - an InDesign file for submission to, for example, a newspaper for a colour advert which will be reproduced in CMYK colour. It may seem quaint that I care about small rural print shops and such antiquities as newspapers, but I assure you they do still exist, they do still need people's logos and they are - generally - far more comfortable with EPS files than any other format. (One must also remember that the site went live in 2013!) So - on balance - I am still quite happy to recommend an EPS file. As things develop, I will hopefully change and update the site. Until then, you are free to submit a pull request with your suggestions, or set up noeps.org. ;)

**Comment by 8lall0** [comment]
Nice answer, thanks @larryhynes :)
